=== godmar/LibX/src/base/chrome/libx/content/libx/preferences/libxprefs.dtd
<!-- DTD for LibX Preferences -->
<!-- $Id: libxprefs.dtd,v 1.1.2.1 2009/02/05 23:58:04 vtdoylem Exp $ -->

<!ELEMENT category (category|preference)+>
<!ATTLIST category 
        name              CDATA #REQUIRED
        layout         	  CDATA #REQUIRED
>


<!ELEMENT preference (item)*>
<!ATTLIST preference 
        name              CDATA #REQUIRED
        type         	  (int|boolean|string|choice|multichoice) 'string'
		value             CDATA #IMPLIED
>


<!ELEMENT item >
<!ATTLIST item 
        value              CDATA #REQUIRED
        type         	   (int|boolean|string) 'string'
	    selected           (selected)     #IMPLIED
>

=== godmar/LibX/src/base/bootstrapped/preferences/contextmenu.prefs.xml
<?xml version="1.0"?>
<!DOCTYPE category SYSTEM "http://libx.org/xml/libxprefs.dtd">
<category layout="tabpanel" name="contextmenu">
  <category layout="tree" name="general">
    <category layout="tree" name="catalog">
      <category layout="tree" name="Addison">
        <preference value="true" name="Y" type="boolean"/>
        <preference value="true" name="t" type="boolean"/>
        <preference value="false" name="jt" type="boolean"/>
        <preference value="true" name="a" type="boolean"/>
        <preference value="false" name="d" type="boolean"/>
        <preference value="false" name="i" type="boolean"/>
        <preference value="false" name="c" type="boolean"/>
      </category>
      <category layout="tree" name="VT Database List">
        <preference value="false" name="dbname" type="boolean"/>
      </category>
      <category layout="tree" name="VT ETD">
        <preference value="false" name="Y" type="boolean"/>
      </category>
      <category layout="tree" name="VT EJournals">
        <preference value="false" name="jt" type="boolean"/>
        <preference value="false" name="i" type="boolean"/>
      </category>
      <category layout="tree" name="Google Scholar">
        <preference value="false" name="Y" type="boolean"/>
        <preference value="false" name="at" type="boolean"/>
        <preference value="false" name="jt" type="boolean"/>
        <preference value="false" name="a" type="boolean"/>
      </category>
      <category layout="tree" name="WorldCat">
        <preference value="false" name="Y" type="boolean"/>
        <preference value="false" name="t" type="boolean"/>
        <preference value="false" name="a" type="boolean"/>
        <preference value="false" name="i" type="boolean"/>
      </category>
    </category>
    <category layout="tree" name="resolver">
      <category layout="tree" name="Get VText">
        <preference value="true" name="jt" type="boolean"/>
      </category>
    </category>
    <category layout="tree" name="scholar">
      <category layout="tree" name="Google Scholar">
        <preference value="true" name="magicsearch" type="boolean"/>
      </category>
    </category>
  </category>
  <category layout="tree" name="isbn">
    <category layout="tree" name="catalog">
      <category layout="tree" name="Addison">
        <preference value="true" name="i" type="boolean"/>
        <preference value="true" name="xisbn" type="boolean"/>
      </category>
      <category layout="tree" name="VT Database List">
        <preference value="false" name="xisbn" type="boolean"/>
      </category>
      <category layout="tree" name="VT ETD">
        <preference value="false" name="xisbn" type="boolean"/>
      </category>
      <category layout="tree" name="VT EJournals">
        <preference value="false" name="i" type="boolean"/>
      </category>
      <category layout="tree" name="WorldCat">
        <preference value="false" name="i" type="boolean"/>
        <preference value="false" name="xisbn" type="boolean"/>
      </category>
    </category>
    <category layout="tree" name="resolver">
      <category layout="tree" name="Get VText">
        <preference value="true" name="i" type="boolean"/>
      </category>
    </category>
  </category>
  <category layout="tree" name="issn">
    <category layout="tree" name="catalog">
      <category layout="tree" name="Addison">
        <preference value="true" name="i" type="boolean"/>
      </category>
      <category layout="tree" name="VT EJournals">
        <preference value="false" name="i" type="boolean"/>
      </category>
      <category layout="tree" name="WorldCat">
        <preference value="false" name="i" type="boolean"/>
      </category>
    </category>
    <category layout="tree" name="resolver">
      <category layout="tree" name="Get VText">
        <preference value="true" name="i" type="boolean"/>
      </category>
    </category>
  </category>
  <category layout="tree" name="doi">
    <category layout="tree" name="resolver">
      <category layout="tree" name="Get VText">
        <preference value="true" name="doi" type="boolean"/>
      </category>
    </category>
  </category>
  <category layout="tree" name="pmid">
    <category layout="tree" name="resolver">
      <category layout="tree" name="Get VText">
        <preference value="true" name="pmid" type="boolean"/>
      </category>
    </category>
  </category>
  <category layout="tree" name="always">
    <category layout="tree" name="proxy">
      <category layout="tree" name="Off Campus Sign In">
        <preference value="true" name="enabled" type="boolean"/>
      </category>
    </category>
  </category>
</category>

=== godmar/LibX/src/unittests/tests/resources/preferences/builtin/browser.prefs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE category SYSTEM "http://libx.org/xml/libxprefs.dtd">
<category name="browser" layout="groups">
  <preference name="displaypref" type="choice">
    <item type="string" value="newtabswitch" selected="true"/>
    <item type="string" value="newtab"/>
    <item type="string" value="sametab"/>
    <item type="string" value="newwindow"/>
  </preference>
  <preference name="autolinking" type="boolean" value="true"/>
  <preference name="citeulike" type="boolean" value="true"/>
</category>
